
# 菜单栏
menu:
  - name: 首页
    url: /
  - name: 分类
    url: /categories/
  - name: 标签
    url: /tags/
  - name: 归档
    url: /archives/
  - name: 友链
    url: /friends/
  - name: 关于
    url: /about/

comment:
  enable: false

search:
  enable: false

friends:
  - name: 阮一峰的网络日志
    avatar: https://avatars.githubusercontent.com/u/905434?v=4
    link: https://www.ruanyifeng.com/blog/
    desc: 互联网科技博主

socialLink:
  - name: Github
    link: https://github.com/pancaiqiang/
  - name: 备案号：京ICP备19040707号-1
    link: http://beian.miit.gov.cn

footer:
  builtUpTime: '2019-12-24 20:00:00'

# 主题色
primaryColor: '#10b981'